config/routes.rb
Rails.application.routes.draw do
  get 'fiscal_year/index'

  get 'fiscal_year/show'

  get 'fiscal_year/new'

  get 'fiscal_year/edit'

  get 'fiscal_year/create'

  get 'fiscal_year/update'

  get 'fiscal_year/newcat'

  get 'fiscal_year/addcat'

  get 'fiscal_year/deletecat'

end

app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :fiscal_year
	belongs_to :category_type
	has_and_belongs_to_many :wbs_versions
	has_many :category_versions
end

app/models/category_budget.rb
class CategoryBudget < ActiveRecord::Base
	belongs_to :category_version
	has_many :category_version_details
end

app/models/category_budget_detail.rb
class CategoryBudgetDetail < ActiveRecord::Base
	belongs_to :category_budget
end

app/models/category_type.rb
class CategoryType < ActiveRecord::Base
	has_many :categories
end

app/models/category_version.rb
class CategoryVersion < ActiveRecord::Base
	belongs_to :category
	has_many :category_versions
end

app/models/category_wbs_version.rb
class CategoryWbsVersion < ActiveRecord::Base
end

app/models/fiscal_year.rb
class FiscalYear < ActiveRecord::Base
	has_many :categories
end

app/models/forecast.rb
class Forecast < ActiveRecord::Base
	belongs_to :wbs_item
	has_many :forecast_details
end

app/models/forecast_detail.rb
class ForecastDetail < ActiveRecord::Base
	belongs_to :forecast
end

app/models/wbs_budget.rb
class WbsBudget < ActiveRecord::Base
	belongs_to :wbs_version
	has_many :wbs_budget_details
end

app/models/wbs_budget_detail.rb
class WbsBudgetDetail < ActiveRecord::Base
	belongs_to :wbs_budget
end

app/models/wbs_item.rb
class WbsItem < ActiveRecord::Base
	has_many :wbs_versions
	has_many :forecasts
end

app/models/wbs_version.rb
class WbsVersion < ActiveRecord::Base
	belongs_to :wbs_item
	has_and_belongs_to_many :categories
	has_many :wbs_budgets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/fiscal_year_controller.rb
class FiscalYearController < ApplicationController
  def index
	  @fiscal_years = FiscalYear.all
  end

  def show
  end

  def new
	  @fiscal_year = FiscalYear.new
  end

  def edit
  end

  def create
  end

  def update
  end

  def newcat
  end

  def addcat
  end

  def deletecat
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fiscal_year_helper.rb
module FiscalYearHelper
end

app/views/fiscal_year/_form.html.erb
<%= form_for @fiscal_year do |f| %>
  <% if @fiscal_year.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fiscal_year.errors.count, "error") %> prohibited this fiscal_year from being saved:</h2>

      <ul>
      <% @fiscal_year.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fiscal_year %><br />
    <%= f.text_field :fiscal_year %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fiscal_year/addcat.html.erb
<h1>FiscalYear#addcat</h1>
<p>Find me in app/views/fiscal_year/addcat.html.erb</p>

app/views/fiscal_year/create.html.erb
<h1>FiscalYear#create</h1>
<p>Find me in app/views/fiscal_year/create.html.erb</p>

app/views/fiscal_year/deletecat.html.erb
<h1>FiscalYear#deletecat</h1>
<p>Find me in app/views/fiscal_year/deletecat.html.erb</p>

app/views/fiscal_year/edit.html.erb
<h1>FiscalYear#edit</h1>
<p>Find me in app/views/fiscal_year/edit.html.erb</p>

app/views/fiscal_year/index.html.erb
<h1>FiscalYear#index</h1>
<p>Find me in app/views/fiscal_year/index.html.erb</p>

<table>
	<tr>
		<th>Year</th>
		<th></th>
		<th></th>
	<tr>
	<% @fiscal_years.each do |fiscal_year| %>
	<tr>
		<td><%= fiscal_year.fiscal_year %></td>
		<td><%= link_to "show", fiscal_year_show_path(fiscal_year) %>
		<td><%= link_to "edit", fiscal_year_edit_path(fiscal_year) %>
	</tr>
	<% end %>
</table>

<br>
<%= link_to "New Fiscal Year", fiscal_year_new_path %>

		
		
		

app/views/fiscal_year/new.html.erb
<h1>FiscalYear#new</h1>
<p>Find me in app/views/fiscal_year/new.html.erb</p>

<%= render 'form' %>

<%= link_to 'Back', fiscal_year_index_path %>

app/views/fiscal_year/newcat.html.erb
<h1>FiscalYear#newcat</h1>
<p>Find me in app/views/fiscal_year/newcat.html.erb</p>

app/views/fiscal_year/show.html.erb
<h1>FiscalYear#show</h1>
<p>Find me in app/views/fiscal_year/show.html.erb</p>

app/views/fiscal_year/update.html.erb
<h1>FiscalYear#update</h1>
<p>Find me in app/views/fiscal_year/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BudgetManager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>